name: Build foo.exe
description: Build foo.exe (on Cygwin)
inputs:
  platform:
    description: Target platform
    required: true
runs:
  using: composite
  steps:
    - run: |
        IFS= read -r src_dir <<'EOF'
        ${{ github.workspace }}
        EOF
        echo "$src_dir"
        src_dir="$( cygpath -ua "$src_dir" )"
        cd -- "$src_dir"
        arch=
        [ '${{ matrix.platform }}' == 'x86' ] && arch=-m32
        g++ $arch -std=c++14 -o foo foo.cpp
      shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
