name: Install GCC
description: Install GCC

inputs:
  version:
    description: GCC version to install
    required: false
    default: latest
  platform:
    description: Target platform
    required: false
    default: x64
  cc:
    description: Set up cc/gcc/c++/g++ executables
    required: false
    default: 1

outputs:
  gcc:
    description: gcc binary name
    value: '${{ steps.install.outputs.gcc }}'
  gxx:
    description: g++ binary name
    value: '${{ steps.install.outputs.gxx }}'

runs:
  using: composite
  steps:
    - id: install
      run: |
        New-Variable os -Value '${{ runner.os }}' -Option Constant

        New-Variable linux_host -Value ($os -eq 'Linux') -Option Constant
        New-Variable windows_host -Value ($os -eq 'Windows') -Option Constant

        New-Variable version -Value ('${{ inputs.version }}') -Option Constant
        New-Variable latest -Value ($version -eq 'latest') -Option Constant
        New-Variable x64 -Value ('${{ inputs.platform }}' -eq 'x64') -Option Constant

        function Locate-Choco {
            $path = Get-Command 'choco' -ErrorAction SilentlyContinue
            if ($path) {
                $path.Path
            } else {
                Join-Path ${env:ProgramData} 'chocolatey' 'bin' 'choco'
            }
        }

        function Enable-TestingPPA {
            sudo add-apt-repository --yes --update ppa:ubuntu-toolchain-r/test
        }

        function Install-Package {
            param(
                [Parameter(Mandatory=$true, ValueFromRemainingArguments=$true)]
                [string[]] $Packages
            )

            if ($script:linux_host) {
                sudo apt-get update
                sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends $Packages
            } elseif ($script:windows_host) {
                $choco = Locate-Choco
                & $choco upgrade $Packages -y --no-progress --allow-downgrade
            } else {
                throw "Sorry, installing packages is unsupported on $script:os"
            }
        }

        if ($linux_host) {
            $pkg = 'g++'
            $gcc = 'gcc'
            $gxx = 'g++'
            if (!$latest) {
                Enable-TestingPPA
                $pkg += "-$version"
                $gcc += "-$version"
                $gxx += "-$version"
            }
            if (!$x64) {
                $pkg += '-multilib'
            }
            Install-Package $pkg
        } elseif ($windows_host) {
            # TODO: use setup-mingw when calling composite actions within
            # composite actions is implemented.
            echo @'
        ::error ::
        Please use the egor-tensin/setup-mingw action to install GCC on Windows.
        '@
            exit 1
        } else {
            throw "Sorry, installing GCC is unsupported on $os"
        }

        echo "gcc=$gcc" >> $env:GITHUB_OUTPUT
        echo "gxx=$gxx" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - run: |
        New-Variable os -Value '${{ runner.os }}' -Option Constant

        New-Variable linux_host -Value ($os -eq 'Linux') -Option Constant
        New-Variable windows_host -Value ($os -eq 'Windows') -Option Constant

        New-Variable cc -Value ('${{ inputs.cc }}' -eq '1') -Option Constant

        New-Variable gcc -Value '${{ steps.install.outputs.gcc }}' -Option Constant
        New-Variable gxx -Value '${{ steps.install.outputs.gxx }}' -Option Constant

        function Link-Exe {
            param(
                [Parameter(Mandatory=$true)]
                [string] $Exe,
                [Parameter(Mandatory=$true)]
                [string] $LinkName
            )

            $exe_path = (Get-Command $Exe).Path
            $link_dir = if ($script:windows_host) { Split-Path $exe_path } else { '/usr/local/bin' }
            $link_name = if ($script:windows_host) { "$LinkName.exe" } else { $LinkName }
            $link_path = Join-Path $link_dir $link_name
            echo "Creating link $link_path -> $exe_path"
            if ($script:linux_host) {
                sudo ln -f -s $exe_path $link_path
            } elseif ($script:windows_host) {
                New-Item -ItemType HardLink -Path $link_path -Value $exe_path -Force | Out-Null
            }
        }

        if ($cc) {
            Link-Exe $gcc cc
            if ($gcc -ne 'gcc') {
                Link-Exe $gcc 'gcc'
            }
            Link-Exe $gxx c++
            if ($gxx -ne 'g++') {
                Link-Exe $gxx 'g++'
            }
        }
      shell: pwsh

branding:
  icon: star
  color: green
